# Variant-specific build arguments.
# Pass to buildah/podman using `--build-arg-file`.

ID=rhel
NAME=rhcos
STREAM=rhel-10.2
DESCRIPTION=Red Hat Enterprise Linux CoreOS 10.2
VERSION=10.2
MUTATE_OS_RELEASE=10.2
BUILDER_IMG=registry.stage.redhat.io/rhel10/rhel-bootc:10.2@sha256:c0ad6aab08deb51d3bf2e0f406546716ae153d0e588c6cf87e1c2fc87cb69e64
MANIFEST=manifest-rhel-10.2.yaml
IMAGE_CONFIG=image-rhel-10.2.yaml
# XXX: see inject_passwd_group() in build-rootfs
PASSWD_GROUP_DIR=.
INJECT_OPENSHIFT_VERSION_LABELS=1
FROM=quay.io/openshift-release-dev/ocp-v4.0-art-dev:4.22-10.2-node-image
