# Variant-specific build arguments.
# Pass to buildah/podman using `--build-arg-file`.
ID=rhel
NAME=rhcos
STREAM=rhel-10.2
VERSION=10.2
FROM=quay.io/openshift-release-dev/ocp-v4.0-art-dev:rhel-10.2-coreos
